services:
  mcp_server:
    container_name: mcp_server
    build: .
    volumes:
      - .:/app
      - app_venv:/app/.venv
    ports:
      - "5555:8000"
    env_file:
      - .env

volumes:
  app_venv: